---
title: "237 w3r"
author: "sunny"
date: "2023-07-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#Textbook question: A fair die is thrown until the sum of the results of the throws exceeds 6.The random variable X is the number of throws needed for this. Let F be thedistribution function of X. Determine F (1), F (2), and F (7).


throw_function = function(){
  draw = sample(c(1:6), size = 2, replace = TRUE)
  t = 2
  s = sum(draw)
  
  while(s <= 6){
    new_draw = sample(c(1:6), size = 1, replace = TRUE)
    t = t + 1
    s = s + new_draw
  }
  
  return(t)
}

function_output = replicate(10000, throw_function())

table(function_output)

```
```{r}
F_1 = (sum(function_output<=1))/10000

print(F_1)
```

```{r}
F_2 = (sum(function_output<=2))/10000

print(F_2)

F_7 = (sum(function_output<=7))/10000

print(F_7)
```


```{r textbook 4.14 question}
ht_function = function(){
  draw1 = sample(c("T","H"), size = 1, replace = TRUE, prob = c(0.75, 0.25))
  t = 1
  if(draw1 == "H"){h_h = 1}else{h_h = 0}
  while(h_h < 2){
    draw2 = sample(c("T", "H"), size = 1, replace = TRUE, prob = c(0.75, 0.25))
    t = t + 1
    if (draw2 == "H"){h_h = h_h + 1}
  }
  return(t)
}
  result = replicate(10000, ht_function())
  
prop.table(table(result))
```

